### ISSUE TITLE
Update and Discord

### ISSUE THREAD

**Issue by CapLeviCorps** [HenryQuan/AnimeGo-Re#26]
Hello. Could you please update the App because it's been quite a while since the last Update. Also could you make a Discord Server for the App where people can join and give Feedback?

**Comment by HenryQuan** [comment]
Hi, happy new year.
I am planning to update the app soon but it is pretty good so far. For the discord server, I have no plan of doing that because Feedback can be posted here on GitHub.

**Comment by CapLeviCorps** [comment]
Hello. Having feedback received here is only ok if you want a few users for the app. But Discord will help you get more users because more people use Discord than GitHub. At least join Discord so that we can talk there because it's easier.

**Comment by HenryQuan** [comment]
That's fine, mate. Thank you for you suggestion. Really appreciate it. I have considered it before but this app is no longer actively maintained anymore as you can see. I have abandoned this project for a year and only returned this year. I am not planning adding any new features other than bug fixes.

**Comment by CapLeviCorps** [comment]
That's sad to know.. I wish you would have still continued development.. That's ok.. Thanks still..

**Comment by HenryQuan** [comment]
Sorry mate...
I may come back one day and rewrite this app in native Android. I will close this issue for now.
