### ISSUE TITLE
Episode detail back button does not return to episode list

### ISSUE THREAD

**Issue by vkhobor** [HenryQuan/AnimeGo-Re#33]
Hi. Thanks for the superb project!

When trying to figure out which episode to watch you have to jump around a lot. 

When pressing the back navigation button from an episode's detail page it goes back two screens, to the search result page, skipping "anime season details"/"episode list" page.

**Comment by HenryQuan** [comment]
Hi, thanks for the feedback. I will take a look at this. I remember there is a reason why it was done this way or maybe just a bug.

**Comment by vkhobor** [comment]
Maybe I will look at this and make a pr if I have time ,and if thats okay. (I am quite a beginner in flutter, thought). I could finally start it up on my phone in debug mode and set up flutter enviroment properly on my machine.

**Comment by HenryQuan** [comment]
That's fine. You can have a look. It is probably something with the `Navigator` but I need to recall why I did it like this. Potentially, I wanted to prevent infinite loop but I think it is really not a big problem.

**Comment by HenryQuan** [comment]
@vkhobor I have found the issue. I think it is my design but clearly, it is very annoying. Please see [this line](https://github.com/HenryQuan/AnimeGo-Re/blob/400bd6c7dbfc3f076bd9a745a98d2b2ea3d3c528/project/lib/ui/page/AnimeDetailPage.dart#L283). Go to branch `update/1.3.1` and change `Navigator.pushReplacement` to `Navigator.push` should fix this issue.
